import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#d1cfce",
        "on-secondary-fixed": "#321200",
        "secondary-container": "#fb7800",
        "primary-fixed-dim": "#b1c5ff",
        "primary-container": "#0051c3",
        outline: "#737785",
        "tertiary-container": "#595858",
        "surface-container-low": "#f3f3f3",
        background: "#f9f9f9",
        "on-primary-container": "#beceff",
        tertiary: "#414141",
        "surface-container-high": "#e8e8e8",
        "on-background": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#ffb68b",
        secondary: "#994700",
        "outline-variant": "#c3c6d6",
        "inverse-on-surface": "#f1f1f1",
        primary: "#003b93",
        "on-error": "#ffffff",
        "inverse-primary": "#b1c5ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#00419f",
        "surface-container": "#eeeeee",
        "surface-bright": "#f9f9f9",
        "primary-fixed": "#dae2ff",
        "on-secondary-container": "#592600",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#474747",
        "on-surface-variant": "#434653",
        "error-container": "#ffdad6",
        "surface-dim": "#dadada",
        "on-surface": "#1a1c1c",
        "inverse-surface": "#2f3131",
        "on-secondary-fixed-variant": "#753400",
        "surface-container-highest": "#e2e2e2",
        "surface-tint": "#1357c9",
        surface: "#f9f9f9",
        "on-tertiary-fixed": "#1b1c1c",
        "tertiary-fixed": "#e4e2e1",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c6",
        "secondary-fixed": "#ffdbc8",
        "on-primary-fixed": "#001947",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["var(--font-inter)"],
        body: ["var(--font-inter)"],
        label: ["var(--font-inter)"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  // v4: Plugins are now auto-detected or imported differently
  plugins: [],
};
export default config;